contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #bactrail channel"
    url: https://nfcore.slack.com/channels/bactrail
    about: Discussion about the nf-core/bactrail pipeline
